# kina_core/billion_builder.py
from typing import Dict
import asyncio
from pathlib import Path
from kina_core.brain import kina_brain
from kina_config.config import config


class KINABillionBuilder:
    """KINA's BILLION line code generator"""

    def __init__(self):
        self.total_lines = 0

    async def build_billions(self, project_name: str, description: str, target_lines: int = 1000000) -> Dict:
        """Generate massive amounts of code"""

        project_dir = config.PROJECTS_DIR / project_name
        project_dir.mkdir(exist_ok=True)

        print(f"🔥 KINA is generating {target_lines:,} lines of code...")
        print("This uses CODE MULTIPLICATION - AI generates templates, KINA multiplies them.\n")

        # Step 1: AI generates the base template
        print("🧠 Step 1: Generating base template...")
        base_code = await self.generate_base_template(description)
        base_code = self.clean_content(base_code)

        if len(base_code) < 100:
            print("❌ AI failed to generate base template")
            return {"success": False}

        # Save base template
        with open(project_dir / "base_template.py", "w", encoding="utf-8") as f:
            f.write(base_code)

        base_lines = base_code.count("\n")
        print(f"   ✅ Base template: {base_lines} lines")

        # Step 2: Generate variations programmatically (NO AI needed)
        print("\n📦 Step 2: Multiplying code...")

        file_count = 0
        total_lines = base_lines

        # Generate 1000 files with variations
        for i in range(1, 1001):
            variation = self.create_variation(base_code, i, description)
            file_path = project_dir / f"src/generated_{i:04d}.py"
            file_path.parent.mkdir(parents=True, exist_ok=True)

            with open(file_path, "w", encoding="utf-8") as f:
                f.write(variation)

            file_count += 1
            total_lines += variation.count("\n")

            if i % 100 == 0:
                print(f"   ✅ {i} files generated ({total_lines:,} lines)")

        # Step 3: Generate more with different templates
        print("\n📄 Step 3: Generating additional templates...")

        for j in range(10):
            new_template = await self.generate_variation_template(description, j)
            new_template = self.clean_content(new_template)

            if len(new_template) > 100:
                for k in range(100):
                    variation = self.create_variation(new_template, k + 1000, description)
                    file_path = project_dir / f"src/variation_{j}_{k:03d}.py"
                    file_path.parent.mkdir(parents=True, exist_ok=True)

                    with open(file_path, "w", encoding="utf-8") as f:
                        f.write(variation)

                    file_count += 1
                    total_lines += variation.count("\n")

            await asyncio.sleep(2)

        # Step 4: Generate README
        readme = f"""# {project_name}

Generated by KINA - AI Development Assistant

## Statistics
- **Files:** {file_count}
- **Lines of code:** {total_lines:,}
- **Description:** {description}

## Structure
- `src/` - Generated code files
- `base_template.py` - Base template

## How to run
```bash
python src/generated_0001.py